package com.oaxaca.menu_service;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class MenuServiceApplicationTests {

	@Test
	void contextLoads() {
	  // Unsure what to test here, MenuServiceApplication was auto-generated by Spring Initializr
	  // Class only has main method and it is very short
	}

}
